<<<<<<< HEAD
version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=riyadh
      - POSTGRES_PASSWORD=restaurant_project
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
=======
version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file: ./.env
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
      TZ: 'GMT+8'
      PGTZ: 'GMT+8'
    networks:
      - dinosaur_backend

  redis:
    image: redis:5.0.6-alpine
    restart: always
    env_file: ./.env
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - dinosaur_backend

networks:
  dinosaur_backend:
    driver: bridge
>>>>>>> ebed19bd45be901eec43898ea0e732acf85d751e
