version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file: ./.env
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
      TZ: 'GMT+8'
      PGTZ: 'GMT+8'
    networks:
      - dinosaur_backend

  redis:
    image: redis:5.0.6-alpine
    restart: always
    env_file: ./.env
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - dinosaur_backend

networks:
  dinosaur_backend:
    driver: bridge
